title: die Holisten
name: die Holisten
lang: de-DE
email: info@holisten.de
description: >- # this means to ignore newlines until "baseurl:"
  die Holisten Partei aus Recklinghausen
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://holisten.de" # the base hostname & protocol for your site, e.g. http://example.com
assets_path: 'assets/'
sass:
  style: compressed
  sass_dir: _sass/
collections:
  projects:
    output: true
    permalink: /themen/:name
twitter:
  username: "@dieholisten"
social:
  links:
    - https://twitter.com/dieholisten
    - https://www.facebook.com/dieholisten/
    - https://github.com/holisten/
# Build settings
markdown: kramdown
kramdown:
  input: GFM
  html_to_native: true
  hard_wrap: false

remote_theme: SotiriosVrachas/jekyll-theme-startbootstrap-agency@0.2.4
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag
permalink: /aktuelles/:year-:month-:day-:title:output_ext
