title: Partei Holistischer Demokratie
name: Partei Holistischer Demokratie
lang: de-DE
email: info@phd-partei.de
description: >- # this means to ignore newlines until "baseurl:"
  Partei Holistischer Demokratie aus Recklinghausen
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://phd-partei.de" # the base hostname & protocol for your site, e.g. http://example.com
assets_path: 'assets/'
sass:
  style: compressed
  sass_dir: _sass/
collections:
  projects:
    output: true
    permalink: /themen/:name/
twitter:
  username: "@holisten3"
social:
  links:
    - https://twitter.com/holisten3
    - https://www.facebook.com/PHD-recklinghausen/
    - https://github.com/holisten/
# Build settings
markdown: kramdown
kramdown:
  input: GFM
  html_to_native: true
  hard_wrap: false
  parse_block_html: true

remote_theme: SotiriosVrachas/jekyll-theme-startbootstrap-agency@0.2.4
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag
  - kramdown-parser-gfm
permalink: /aktuelles/:year-:month-:day-:title:output_ext/
