brand:
  name: die Holisten
menu-string: Menu

nav:
  - title: Recklinghausen
    url: 'recklinghausen/'
  - title: Europa
    url: 'europa/'
  - title: Partei
    url: 'partei/'
  - title: Themen
    url: 'themen/'

copyright: Copyright &copy; die Holisten 2019

social-buttons:
  - icon: fab fa-facebook
    url: 'https://www.facebook.com/dieholisten/'
  - icon: fab fa-instagram
    url: 'https://www.instagram.com/die_holisten/'

quicklinks:
  - title: Datenschutz
    url: '/site/datenschutz/'
  - title: Kontakt & Impressum
    url: '/site/impressum/'
