brand:
  name: Partei Holistischer Demokratie
menu-string: Menu

nav:
  - title: Recklinghausen
    url: 'recklinghausen/'
  - title: Partei
    url: 'partei/'
  - title: Themen
    url: 'themen/'

copyright: Copyright &copy; PHD 2020

social-buttons:
  - icon: fab fa-facebook
    url: 'https://www.facebook.com/PHD.recklinghausen/'
  - icon: fab fa-instagram
    url: 'https://www.instagram.com/phd_recklinghausen/'
  - icon: fab fa-youtube
    url: 'https://www.youtube.com/channel/UCVUjxCY5fYkbuR7-27iy3gw'

quicklinks:
  - title: Datenschutz
    url: '/site/datenschutz/'
  - title: Kontakt & Impressum
    url: '/site/impressum/'
