brand:
  name: die Holisten
menu-string: Menu

nav:
  - title: Recklinghausen
    url: 'recklinghausen'
  - title: Europa
    url: 'europa'
  - title: Welt
    url: 'welt'
  - title: Partei
    url: 'partei'
  - title: Aktuelles
    url: 'aktuelles'

copyright: Copyright &copy; die Holisten 2019

social-buttons:
  - icon: fab fa-twitter
    url: '#' 
  - icon: fab fa-facebook
    url: '#'
  - icon: fab fa-youtube
    url: '#'
  - icon: fab fa-instagram
    url: '#'

quicklinks:
  - title: Kontakt
    url: '/site/kontakt'
  - title: Datenschutz
    url: '/site/datenschutz'
  - title: Impressum
    url: '/site/impressum'
