---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: partei
  label: Partei & Programm
  create: documents
  match: "**/*"
- type: jekyll-posts
  label: News-Artikel
  create: documents
  templates:
  - neuer-news-eintrag
- type: directory
  path: _projects
  label: Themen
  create: documents
  match: "**/*"
  templates:
  - neues-thema-vorlage
- type: directory
  path: recklinghausen
  label: Recklinghausen
  create: documents
  match: "**/*"
  templates:
  - textinhalt
- type: directory
  path: europa
  label: Europa
  create: documents
  match: "**/*"
  templates:
  - textinhalt
  - textinhalt
- type: directory
  path: welt
  label: Welt
  create: documents
  match: "**/*"
  templates:
  - textinhalt
upload_dir: assets/img/content
public_path: "/assets/img/content"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
